---
title: Bildungsdimension
author: Niels Michalski, Marvin Reis
date: '2021-07-15'
slug: []
categories:
  - R
tags:
  - R Markdown
  - plot
weight: 1
---

# Bildungsdimension

```{r setup, include=FALSE}
library("ggplot2")
library("rkicolors")
library("dplyr")

knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries und Datengeniererung, include=FALSE}

#Impdata.imputed <- readRDS("C:/projects_rstudio/GISD/Outfiles/Impdata_check.rds")
#Resultdataset <- read.csv("C:/projects_rstudio/GISD/Outfiles/2021/Bund/Gemeinde/Gemeinde.csv")

Impdata.imputed <- readRDS("C:/git_projects/GISD/Outfiles/Impdata_check.rds")
Resultdataset <- readRDS("C:/git_projects/GISD/Outfiles/Resultdataset.rds")

Corr_data <- left_join(as.data.frame(Impdata.imputed), Resultdataset, all.x = TRUE)

Corr_data <- Corr_data %>% mutate(Jahr=as.factor(Jahr))

# Idee für spätere Analysen: Variablen auf Basis von Percentilen
Corr_data <- Corr_data %>%  mutate(alos_q = findInterval(Arbeitslosigkeit, quantile(Arbeitslosigkeit,   probs=0:100/100, type=9)), alos_q = findInterval(alos_q, c(1:100)), beschAkad_q = findInterval(BeschaeftigtemitakadAbschluss, quantile(BeschaeftigtemitakadAbschluss,   probs=0:100/100 , type=9)),  beschAkad_q = findInterval(beschAkad_q, c(1:100)))
```

```{r Bildungsdimension Plots, echo=FALSE}
ggplot(Corr_data, aes(GISD_Score, Jahr, color = BeschaeftigtemitakadAbschluss)) + geom_tile(alpha = 0.5, size = 0.5) +
  theme_rki() + theme(legend.position="bottom") + 
  scale_color_gradientn(colours = rainbow(5)) + scale_y_discrete(limits=rev) + 
  scale_x_continuous(position = "top") +
  labs(colour = "Anteil Beschäftigter mit akademischem Abschluss", x = "GISD Score", title = "Verteilung von akadem. Beschäftigten auf den GISD-Score") 

ggplot(Corr_data, aes(GISD_Score, Jahr, color = BeschaeftigteohneAbschluss)) + geom_tile(alpha = 0.5, size =0.5) + 
  theme_rki() + theme(legend.position="bottom") + 
  scale_color_gradientn(colours = rainbow(5)) + scale_y_discrete(limits=rev) + 
  scale_x_continuous(position = "top") +
  labs(colour = "Anteil Beschäftigter ohne Abschluss", x = "GISD Score", title = "Verteilung der Beschäftigten ohne Abschluss auf den GISD-Score") 

ggplot(Corr_data, aes(GISD_Score, Jahr, color = BeschaeftigteohneAbschluss_adj)) + geom_tile(alpha = 0.5, size =0.5) +
  theme_rki() + theme(legend.position="bottom") + 
  scale_color_gradientn(colours = rainbow(5)) + scale_y_discrete(limits=rev) + 
  scale_x_continuous(position = "top") +
  labs(colour = "Anteil Beschäftigter ohne Abschluss (adjusted)", x = "GISD Score", title = "Verteilung der Beschäftigten ohne Abschluss (adj.) auf den GISD-Score")

ggplot(Corr_data, aes(GISD_Score, Jahr, color = SchulabgaengerohneAbschluss)) + geom_tile(alpha = 0.5, size =0.5) + 
  theme_rki() + theme(legend.position="bottom") + 
  scale_color_gradientn(colours = rainbow(5), limits=c(0,25)) + scale_y_discrete(limits=rev) + 
  scale_x_continuous(position = "top") +
  labs(colour = "Anteil der Schulabgänger ohne Abschluss", x = "GISD Score", title = "Verteilung der Schulabgänger ohne Abschluss auf den GISD-Score") 

ggplot(Corr_data, aes(GISD_Score, Jahr, color = SchulabgaengerohneAbschluss_adj)) + geom_tile(alpha = 0.5, size =0.5) + theme_rki() + theme(legend.position="bottom") + 
  scale_color_gradientn(colours = rainbow(5), limits=c(0,25)) + scale_y_discrete(limits=rev) + 
  scale_x_continuous(position = "top") +
  labs(colour = "Anteil der Schulabgänger ohne Abschluss (adjusted)", x = "GISD Score", title = "Verteilung der Schulabgänger ohne Abschluss (adj.) auf den GISD-Score") 

ggplot(Corr_data, aes(GISD_Score, Jahr, color = SchulabgaengermitHochschulreife)) + geom_tile(alpha = 0.5, size =0.5) + theme_rki() + theme(legend.position="bottom") + 
  scale_color_gradientn(colours = rainbow(5), limits=c(0,70)) + scale_y_discrete(limits=rev) + 
  scale_x_continuous(position = "top") +
  labs(colour = "Anteil der Schulabgänger mit Hochschulreife", x = "GISD Score", title = "Verteilung der Schulabg. mit Hochschulreife auf den GISD-Score") 

ggplot(Corr_data, aes(GISD_Score, Jahr, color = SchulabgaengermitHochschulreife_adj)) + geom_tile(alpha = 0.5, size =0.5) +
  theme_rki() + theme(legend.position="bottom") + 
  scale_color_gradientn(colours = rainbow(5), limits=c(0,70)) + scale_y_discrete(limits=rev) + 
  scale_x_continuous(position = "top") +
  labs(colour = "Anteil der Schulabgänger mit Hochschulreife (adjusted)", x = "GISD Score", title = "Verteilung der Schulabg. mit Hochschulreife (adj.) auf den GISD-Score")
```